# Generated by Django 5.2.2 on 2025-06-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_socio_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
