# Generated by Django 5.2.2 on 2025-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_socio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='inactive_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='inactive_status',
            field=models.CharField(blank=True, choices=[('vacaciones', 'Vacaciones'), ('temporal', 'Ausencia Temporal'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
