# Generated by Django 5.2.2 on 2025-06-19 18:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_en_vacaciones_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.producto_foto_path),
        ),
    ]
