# Generated by Django 4.2.23 on 2025-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_fix_en_vacaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
