# Generated by Django 4.2.23 on 2025-07-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_producto_foto_alter_socio_foto'),
        ('api', '0012_replace_dots_in_pago_id'),
    ]

    operations = [
    ]
